### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ghost**
The `pacman-key` commands should be run as root.

### CODE REVIEW

**Review by PedroHLC — CHANGES_REQUESTED** [review]
:thinking: I never consider `#` as root-shell, it's much more used like a comment.

But instead, let's drop this, and have a:
```css
code.sh::before {
  content: '# ';
}
```

This way, it does not get selected when someone wants to copy the command:
image

**EDIT**: Needs to bump last-edit.

**Comment by ghost** [comment]
Well, I had been pretty familiar with the convention of using '#' to denote a root shell. Nevertheless, this was just a small detail that I noticed and decided to let you know.

**Comment by PedroHLC** [comment]
> Well, I had been pretty familiar with the convention of using '#' to denote a root shell. Nevertheless, this was just a small detail that I noticed and decided to let you know.

Np, do you believe you can add the changes I suggested?:
1. Bdd that rule with "#" to the `style.css`;
2. Remove the "#" from the HTML;
3. bump the last-edit on the footer.

**Comment by namanlp** [comment]
Sorry for late response. This has been solved with latest commit 
https://github.com/chaotic-aur/chaotic-aur.github.io/commit/b5ead0c37d7a784462a08d0f4287185be6cdee23

**Comment by dr460nf1r3** [comment]
Very nice :)

**Comment by PedroHLC** [comment]
@namanlp `paru`'s commands should not run as root.

**Comment by namanlp** [comment]
Oh, ok, this commit should do it.

https://github.com/chaotic-aur/chaotic-aur.github.io/commit/f62adefc7bb1957c9460893e5328231d612bf110

Is it okay now?

**Comment by PedroHLC** [comment]
> Is it okay now?

Fantastic work!

Also, kudos to @pratik-devkota's contribution.

**Pull request closed without merging**
